### ISSUE TITLE
sched_getaffinity() limits use of domain isolated cores

### ISSUE THREAD

**Issue by seanvk** [igaw/jitterdebugger#18]
https://github.com/igaw/jitterdebugger/commit/f4f43d631a3fb005846592337d41a5168bb96682

When doing some latency tests with isolcpus=nohz,domain,1-7 with 0 as irq affinity and for housekeeping, suddenly discovered I was no longer able to test with -a1-7 with jitterdebugger.  If I wish to test isolated cores that I isolated the domains for, it seems to defeat the purpose for someone wanting to experiment with a finely tuned system.  Cyclictest does not limit use with sched_getaffinity() in comparison and neither did jitterdebugger until this change.

From an RT perspective, I like to think of myself as the curator of the cores and their availability so when I use tools like jitterdebugger, I would prefer to be able to test what I want to test regardless of whether or not the domain is isolated.  And in this case, I'm the one doing the isolation at the domain level for good reason.  

So I would prefer to revert this change.

Sean

**Comment by igaw** [comment]
What about allowing the -a argument to overrule the default settings instead? I do think jitterdebugger should behave correctly if -a is not given as I tried to point out in the commit message.

**Comment by seanvk** [comment]
@igaw Allowing the -a argument to overrule the default makes sense.

**Comment by vt-alt** [comment]
Same issue here. I still want to test and see latency when core is in `isolcpus=`.

**Comment by igaw** [comment]
Fixed b90ff3a30e2a0694fd2c61f7f0d2591152f2c2a2
