### ISSUE TITLE
The first measurement cycle uses interval*2 

### ISSUE THREAD

**Issue by fbezdeka** [igaw/jitterdebugger#19]
Taken  from  jitterdebugger.c:
```c
static void *worker(void *arg)
...
	next = ts_add(now, interval);

	while (!READ_ONCE(jd_shutdown)) {
		next = ts_add(next, interval);
...
```
That means that the first measurement cycle does not use `interval` but `interval * 2 ` instead.

Is that considered as warmup phase or just a bug?

**Comment by igaw** [comment]
I'd say this is a bug. I think I just wanted to initialize next but accidentally copied the update line instead just a plain 'next = now'.

Just a sec, I fix it up.

**Comment by igaw** [comment]
Fixed in dd09822284a623ee945bc57db3f50e0089a489a7

**Comment by fbezdeka** [comment]
Thanks for the super fast response and fix!

**Comment by igaw** [comment]
You are welcome. It was easy after all :)
