### ISSUE TITLE
Looking for explanation of weird results

### ISSUE THREAD

**Issue by hameerabbasi** [igaw/jitterdebugger#21]
Hello, I have some jitterdebugger results where each CPU seems to have a distinct offset to its measurements, but otherwise they have the same profile. I was hoping to get an explanation, or if these are valid results.

Here is the results archive:
[realtime-execution-and-validation-develop-results-GEL-191-cpu-config-test-run-smt-off-cstates-on-performance-5m-stress-cpu-jd.tar.gz](https://github.com/igaw/jitterdebugger/files/7602788/realtime-execution-and-validation-develop-results-GEL-191-cpu-config-test-run-smt-off-cstates-on-performance-5m-stress-cpu-jd.tar.gz)

**Comment by igaw** [comment]
FTR, it looks like this:
![image](https://user-images.githubusercontent.com/1050803/143608086-24c0bc55-23f8-4147-b51e-6390156450ef.png)

My first instinct says, the timers are firing with the offset.

But first I would check if cyclictest shows the same offset problem. Note, the default wake up interval is 1000us for jitterdebugger whereas cyclictest uses different interval defaults. I suggest you set the default interval in cyclictest also to 1000us to reduce the numbers of variables.

**Comment by hameerabbasi** [comment]
Hey! Thanks for getting back to me. We matched the values for JitterDebugger and Cyclictest exactly (including the 1000 us interval and difference of 0 us) and it didn't reproduce these patterns. The behaviour persists over multiple runs of both tools, so it isn't a one-off.

**Comment by igaw** [comment]
Thanks for verifying it with cyclictest. This means it's not jitterdebugger doing something wrong.

That said, I think you need to get in touch with the kernel folks (I suggest you just mention cyclictest as it is more known and avoids confusion). I think it looks like there is a hickup with the timers.

**Comment by hameerabbasi** [comment]
Oh, I think I was unclear in my explanation: It happens for jotterdebugger every time and never for cyclictest.

**Comment by hameerabbasi** [comment]
It turns out this wass due to the cyclictest option `--secaligned`

**Comment by igaw** [comment]
Uhh, was not aware of this option. It sounds like a dangerous corner case option :) Thanks for the feedback!
