### ISSUE TITLE
Sampling in nanoseconds

### ISSUE THREAD

**Issue by xentec** [igaw/jitterdebugger#9]
We already had some discussions and I'd to continue them in a single place.

Here is a summary how sampling for histogram currently works:
- for every worker thread allocate a bucket array (`uint64_t`) with size of 1000 (1000 µs in 1 ms, which is our sample range)
- increment bucket with latency occurrence measured in working thread
- ignore latencies outside the sample range

The last point is not ideal and can easily be fixed with a overflow list array. PR coming soon:tm:.

Now to sample in nanoseconds we need to expand the sample range to 1000000 (ns in 1 ms) which are 8 MiB for every thread.
From https://github.com/igaw/jitterdebugger/pull/3#pullrequestreview-187057810 your suggestion, Daniel, was to sample only in nanoseconds and convert to microseconds where needed. And to reduce needless memory usage, bucket size could be set independently via option.

Since bucket size is tied directly to sampling range, which the user probably would like to specify, I'm not sure if we should call that option 'bucket-size'. But then again we have overflow arrays for misfits.

IMO, ideally instead of microseconds or nanoseconds the user could specify a range in-between 1 ms and 1 ns which would be the bucket size and depending how fine it goes a fitting unit would be choosen.
As example for option: `--sample-range <begin-in-ns>-<end-in-ns>` 
- `--sample-range 1-10000`: 1 ns to 10 µs, bucket size 10000, unit ns
- `--sample-range 100-100000`: 100 ns to 100 µs, bucket size 1000, unit ns
- `--sample-range 1000-1000000`: 1 µs to 1 ms, bucket size 1000, unit µs

or maybe better syntax: `--sample-range <lowest-unit-factor>,<sample-range-size>`
- `--sample-range 1,10000`: from 1 ns, bucket size 10000, unit ns
- `--sample-range 100,1000`: from 100 ns, bucket size 1000, unit ns
- `--sample-range 1000,1000`: from 1 µs, bucket size 1000, unit µs

Waiting to hear your thoughts Daniel and also @rralf.

**Comment by xentec** [comment]
Ping @igaw

**Comment by igaw** [comment]
Sorry for the extreme long delay. 

- ignore latencies outside the sample range: I don't see a need to create a perfect histogram during runtime. If you really want to create a complete histogram do it after termination or via an external tool (jitterdebugger can stream the data direclty). The build in histogram is just a short cut to see something immediately, espicially I don't think it's a good idea to have any work in the measurement loop. All calculation stuff should happen outside of the critical section. Adding a dynamic data structure in there is something we should really avoid.

- bucket size: if the user has to provide this kind of arguments to the tool we make it hard to use correctly.. The main idea of this tool is, just run it, it does the right thing. Could we not do all this fancy stuff outside of the main tool? I wonder if the histogram part should not be outside the main tool..... What about creating a plugin interface and implement different plugins. So the first thing would to move the current histogram code into (default?) plugin. You could then have a high resolution histogram etc. We could also move the streaming code into plugin. I really would like to keep the main program as simple as possible. 

What do think?

**Comment by xentec** [comment]
> Sorry for the extreme long delay.

I don't mind. My fork got the features I want. ;)

>* ignore latencies outside the sample range: I don't see a need to create a perfect histogram during runtime. If you really want to create a complete histogram do it after termination or via an external tool (jitterdebugger can stream the data direclty). The build in histogram is just a short cut to see something immediately, espicially I don't think it's a good idea to have any work in the measurement loop. All calculation stuff should happen outside of the critical section. Adding a dynamic data structure in there is something we should really avoid.

The overflow list wouldn't be dynamic. It's another allocated array (like `hist`), but with jitter occurrences appended instead of counted in buckets. When overflow list searches it's capacity, no reallocation would occur. It just would drop jitter not fitting into `hist`.

> * bucket size: if the user has to provide this kind of arguments to the tool we make it hard to use correctly.. The main idea of this tool is, just run it, it does the right thing. Could we not do all this fancy stuff outside of the main tool? I wonder if the histogram part should not be outside the main tool..... 
What about creating a plugin interface and implement different plugins. So the first thing would to move the current histogram code into (default?) plugin. You could then have a high resolution histogram etc. We could also move the streaming code into plugin. I really would like to keep the main program as simple as possible.
>
> What do think?

It seems to me that you want a master-slave/server-client architecture, where slaves do the measuring (like JD does now, but bare minimum) and send everything to master for further processing (i.e. histogram, other plugins). 
I hope hope my guess is right, because I like the idea.

**Comment by igaw** [comment]
Yes, I would like to split the measurement loop and the 'visualization' part from each other. That makes it more flexible also for the things I have in the pipe :)

**Comment by igaw** [comment]
I added a simple plugin infrastructure for jittersamples which could be reused for jitterdebugger. So we could just add different measurement loops/online evaluation etc as plugin.

**Comment by igaw** [comment]
I just added nanoseconds support with c46c1b5d3aef ("jitterdebugger: Add support for nano seconds resolution"). Let's see how things go awry :)
